baseURL = 'https://www.georgialeng.com'
languageCode = 'en-us'
title = 'Georgia Leng'
theme = 'cactus'

[params]
  scheme = "preference" # light, dark, gray or preference
  mainSectionTitle = "Writings"
  description = "DevOps Engineer . Birdwatcher . SpineSufferer"

  [[menu.main]]
    name = "About me"
    url = "/page/about-me"
