baseURL = 'https://www.georgialeng.com'
languageCode = 'en-us'
title = 'Georgia Leng'
theme = 'cactus'

[params]
  scheme = "preference" # light, dark, gray or preference
  mainSectionTitle = "Recent"
  description = "DevOps Engineer . Birdwatcher . SpineSufferer"


  [[menu.main]]
    name = "About me"
    url = "/page/about-me"
  [[menu.main]]
    name = "Writings"
    url = "/page"

[taxonomies]
  category = 'categories'
  topic = 'topics'
  tag = 'tags'

